common equil_param,Bmodel,Rmajor,aminor,B_tor0,upperelong,lowerelong,uppertri,lowertri,z0,shafranov0,qprof,qprof_rho,efit_file,efit_shot,efit_time,Ermodel,Er_r,Er_val,Er_diamagnetic,Er_vtheta,Er_vphi
